### ISSUE TITLE
进入BootOS后，没有将SN等信息注册到资源池管理

### ISSUE THREAD

**Issue by kkxue** [idcos/osinstall-server#17]
服务器型号：HP SE316M1(是不是旧服务器不支持？)
服务器可以获取SN的：
[root@node2 ~]# dmidecode |grep "Serial Number"
    Serial Number: USE949N8AH    
但是，
服务器加电，进入BootOS后，**没有**将SN等信息注册到【资源池管理】【新发现设备列表】

**Comment by yunji-devin** [comment]
请在设备进入BootOS后，检查下/var/log/cloudboot-agent.log，有啥异常？

**Comment by kkxue** [comment]
是在cloudboot服务端吧，没有找到该日志文件

**Comment by yunji-devin** [comment]
在客户机，BootOS里检查

**Comment by kkxue** [comment]
需要纠正下，没有进入到BootOS，就是停止在选择BootOS界面，进不去

**Comment by kkxue** [comment]
那就是另外一个issue了，谢谢 @yunji-devin

**Comment by kkxue** [comment]
今天重新搭建环境测试后，已经解决这个问题，原因是需要修改BootOS中的tftp启动文件，需要修改osinstall.idcos.com域名为对应的cloudboot服务器的IP地址，详见http://idcos.github.io/osinstall-doc/bootos/BootOS%E4%BD%BF%E7%94%A8.html
