### ISSUE TITLE
centos6.7系统模版没有加%end问题

### ISSUE THREAD

**Issue by kkxue** [idcos/osinstall-server#19]
你好，我在centos6.7系统模板的基础上复制了一份来做centos7系统模板，修改了一些参数（只是版本）
但是在安装部署的时候，报如下错误(%pre和%post类似)：
Section %packages does not end with %end
搜索了下，说是必须要加上%end
原话是"Sections %addon, %packages, %pre and %post must end with %end, otherwise the installation program will refuse the Kickstart file."
由于我没有测试过，我想问，centos6.7模板里没有加%end也不会报错么？
参考：https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Installation_Guide/sect-kickstart-howto.html#sect-kickstart-file-create

**Comment by wangsu728** [comment]
centos6 可以不加 %end，但是 centos7 必须要加
