### ISSUE TITLE
1.5.1版本，安装win2012r2会停在ping osinstall这，请问怎么处理？

### ISSUE THREAD

**Issue by wanghy8166** [idcos/osinstall-server#29]
1.5.1版本，安装win2012r2中，在执行peconfig会停在ping osinstall，ping timeout这，请问怎么处理？

**Comment by wangsu728** [comment]
有可能是 winpe 中没有对应的网卡驱动，执行 ipconfig /all 命令看下有没有对应的本地连接以及是否获取到了正确的 ip 地址。如果是驱动问题，那么需要更新 winpe 镜像

**Comment by wanghy8166** [comment]
这个是在 /opt/cloudboot/etc/dhcp/dhcpd.conf 中修改一行配置
option domain-name "idcos.com";
用域名，不要用ip

**Comment by gittars** [comment]
我遇到了网卡驱动的问题，我的网卡是Realtek1000M。更新winpe镜像加了很多网卡驱动（万能网卡以及PROWinx64.exe Windows 10，64 位*），还是提示没有找不到网卡驱动。
我想请问下winpe需要的网卡驱动是否有版本一说？或者请指导下我应该加什么网卡驱动，谢谢~

**Comment by wangsu728** [comment]
> 我遇到了网卡驱动的问题，我的网卡是Realtek1000M。更新winpe镜像加了很多网卡驱动（万能网卡以及PROWinx64.exe Windows 10，64 位*），还是提示没有找不到网卡驱动。
> 我想请问下winpe需要的网卡驱动是否有版本一说？或者请指导下我应该加什么网卡驱动，谢谢~

你好，驱动程序必须跟操作系统版本对应。如果是 2008 的 winpe 则需要集成 2008 版本的网卡驱动。

**Comment by gittars** [comment]
我正在使用cloudboot-1.4-1.x86_64.rpm这个版本，请教下这个版本包里的winpe是哪个版本啊？

**Comment by wangsu728** [comment]
> 我正在使用cloudboot-1.4-1.x86_64.rpm这个版本，请教下这个版本包里的winpe是哪个版本啊？

自带的 winpe 是 windows 2008r2
