### ISSUE TITLE
修改数据库为postgres数据库引入第三方lib后执行gb build报错

### ISSUE THREAD

**Issue by Heyaah** [idcos/osinstall-server#6]
修改osinstall-server/src/model/mysqlrepo下的repo.go文件，添加  _ "github.com/lib/pq"
go get github.com/lib/pq
cd osinstall-server/
执行gb build出现如下错误
FATAL: command "build" failed: failed to resolve import path "cmd/cloudboot-server": import "github.com/lib/pq": not found: stat /root/osinstall-server/src/github.com/lib/pq: no such file or directory

**Comment by voidint** [comment]
1、当前所有的持久层操作都是针对`mysql`，对于其他的关系型数据库，未测试有效性。
2、粗看这里的gb build报错信息，估计是您没有将第三方库`github.com/lib/pq`引入gb vendor，建议在项目根目录下执行`gb vendor fetch github.com/lib/pq`。您执行的`go get github.com/lib/pq`只是将库在您本地`GOPATH`下安装了，而这里是使用`gb`管理依赖，建议查看[gb usage](https://getgb.io/docs/usage/)。
3、很抱歉没有及时回复。

**Comment by Heyaah** [comment]
问题已解决，感谢您的解答！
            在2016年12月26日 14:56，voidint 写道:1、当前所有的持久层操作都是针对mysql，对于其他的关系型数据库，未测试有效性。
2、粗看这里的gb build报错信息，估计是您没有将第三方库github.com/lib/pq引入gb vendor，建议在项目根目录下执行gb vendor fetch github.com/lib/pq。您执行的go get github.com/lib/pq只是将库在您本地GOPATH下安装了，而这里是使用gb管理依赖，建议查看gb usage。
3、很抱歉没有及时回复。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/idcos/osinstall-server","title":"idcos/osinstall-server","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/idcos/osinstall-server"}},"updates":{"snippets":[{"icon":"PERSON","message":"@voidint in #6: 1、当前所有的持久层操作都是针对`mysql`，对于其他的关系型数据库，未测试有效性。\r\n2、粗看这里的gb build报错信息，估计是您没有将第三方库`github.com/lib/pq`引入gb vendor，建议在项目根目录下执行`gb vendor fetch github.com/lib/pq`。您执行的`go get github.com/lib/pq`只是将库在您本地`GOPATH`下安装了，而这里是使用`gb`管理依赖，建议查看[gb usage](https://getgb.io/docs/usage/)。\r\n3、很抱歉没有及时回复。"}],"action":{"name":"View Issue","url":"https://github.com/idcos/osinstall-server/issues/6#issuecomment-269172855"}}}
